server:
  port: 8081
spring:
  application:
    name: wxshop
  #  数据库驱动
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root
  # 缓存
  redis:
    host: localhost
    port: 6379
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logback:
  config: classpath:log/logback-spring.xml
wxshop:
  orderservice:
    version: 1.0.0
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
